### ISSUE TITLE
Invalid format string

### ISSUE THREAD

**Issue by zelein** [cmaron/CS-7641-assignments#1]
I am getting this error in Windows, but not in OSX.

Run with these params `--seed 55 --threads 4 --dt`

```
Traceback (most recent call last):
  File ".\run_experiment.py", line 89, in <module>
    run_experiment(experiment_details, experiments.DTExperiment, 'DT', verbose, timings)
  File ".\run_experiment.py", line 20, in run_experiment
    exp.perform()
  File "D:\gatech\7641\all\assignment1\experiments\DT.py", line 38, in perform
    verbose=self._verbose)
  File "D:\gatech\7641\all\assignment1\experiments\__init__.py", line 279, in perform_experiment
    best_params=best_params, threads=threads, seed=seed)
  File "D:\gatech\7641\all\assignment1\experiments\__init__.py", line 106, in basic_results
    ts = datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S.%s')
ValueError: Invalid format string
```

**Comment by zelein** [comment]
Could potentially by my version of python3.

OSX is on `3.7.2` and Windows is on `3.6.5`

**Comment by cmaron** [comment]
Ah, good catch. Indeed based on the python docs for strftime there is no valid `%s`. Funky. Can you change it to `%f` and confirm it's fine in windows? I'll test on OS X and linux

**Comment by cmaron** [comment]
Merged a PR @zelein, let me know if it works for you.

**Comment by zelein** [comment]
Yep, works for me on Windows.
