### ISSUE TITLE
Assignment 2 : Neural network bits fail with java.lang.IndexOutOfBoundsException

### ISSUE THREAD

**Issue by timuster** [cmaron/CS-7641-assignments#6]
Running the following files with Jython throws an Index out of bounds error.

- NN-Backprop.py
- NN-GA.py
- NN-RHC.py
- NN-SA.py

`$ jython NN-Backprop.py`

Using seed 653091685

Error results for Backprop
---------------------------
Traceback (most recent call last):
  File "NN-Backprop.py", line 48, in <module>
    main()
  File "NN-Backprop.py", line 38, in main
    train(BatchBackPropagationTrainer(data_set, classification_network, measure, rule), classification_network,
  File "/CS-7641-assignments/assignment2/base.py", line 132, in train
    oa.train()
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
	at java.base/java.util.Objects.checkIndex(Objects.java:372)
	at java.base/java.util.ArrayList.get(ArrayList.java:440)
	at func.nn.Layer.getNode(Layer.java:43)
	at func.nn.Layer.setActivations(Layer.java:60)
	at func.nn.LayeredNetwork.setInputValues(LayeredNetwork.java:53)
	at func.nn.backprop.BatchBackPropagationTrainer.train(BatchBackPropagationTrainer.java:46)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)

java.lang.IndexOutOfBoundsException: java.lang.IndexOutOfBoundsException: Index 8 out-of-bounds for length 8
`

**Comment by timuster** [comment]
- I tested this on both MacOS and Ubuntu (Jython was installed using the official download jar)
- I did run `python run_experiment.py --dump_data` and the 3 'toy-problems' before trying to run the 4 NN scripts mentioned above.

**Comment by timuster** [comment]
`$ jython --version`
Jython 2.7.0

`$ java --version`
openjdk 10.0.2 2018-07-17
OpenJDK Runtime Environment (build 10.0.2+13-Ubuntu-1ubuntu0.18.04.4)
OpenJDK 64-Bit Server VM (build 10.0.2+13-Ubuntu-1ubuntu0.18.04.4, mixed mode)

**Comment by timuster** [comment]
I figured that this can be resolved by properly setting the input layer size in the specific files... I'll let this issue stay 'open' in case you'd like help updating the README (post a comment and I can create a pull-request).

Thanks for the project, Chad!

**Comment by cmaron** [comment]
If I'm following correctly you're saying the `INPUT_LAYER` and `OUTPUT_LAYER` settings have to be changed for the data sets and that's not clear in the readme? If so feel free to open a PR. An alternative might be to update `base.py` in order specify these settings in one place, similar to how `DS_NAME` is set there. In fact all those layer settings should probably be in `base.py`...

**Comment by sw-yx** [comment]
agree, ran into this exact issue. thanks for filling the issue @timuster. happy to help move up those settings once i finish catching up on this dang assignment...

**Comment by cmaron** [comment]
@timuster and @sw-yx I've updated the readme, let me know if you have more to add.
